<script setup>
import { useNotyf } from "../composables/useNotyf";

const notif = useNotyf();

const loading = ref(false);
const allPosts = ref([]);
const searchText = ref("");
const searchTimeout = ref(null);
const searchedResults = ref([]);

const fetchPosts = async () => {
  loading.value = true;

  try {
    const response = await fetch("http://localhost:8080/api/v1/post", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (response.ok) {
      const result = await response.json();
      allPosts.value = result.data.reverse();
    }
  } catch (err) {
    console.error(err.reponse);
    notif.error(err.reponse.data.error);
  } finally {
    loading.value = false;
  }
};

const handleSearchChange = (e) => {
  clearTimeout(searchTimeout);
  console.log("event", e.target.value);
  searchText.value = e.target.value;

  searchTimeout.value = setTimeout(() => {
    const searchResults =
      allPosts.value.filter((item) =>
        item.name.toLowerCase().includes(searchText.value.toLowerCase())
      ) || item.prompt.toLowerCase().includes(searchText.value.toLowerCase());

    searchedResults.value = searchResults;
  }, 500);
};

onMounted(() => {
  fetchPosts();
});
</script>
<template>
  <section class="max-w-7xl mx-auto">
    <div>
      <h1 class="font-extrabold text-[#222328] text-[32px]">
        The Community Showcase
      </h1>
      <p class="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>

    <div class="mt-16">
      <FormField
        v-model="searchText"
        labelName="Search posts"
        type="text"
        name="text"
        placeholder="Search something..."
        @handleChange="handleSearchChange"
      />
    </div>

    <div class="mt-10">
      <div v-if="loading" class="flex justify-center items-center">
        <Loader />
      </div>
      <template v-else>
        <h2 v-if="searchText" class="font-medium text-[#666e75] text-xl mb-3">
          Showing Resuls for <span class="text-[#222328]">{{ searchText }}</span
          >:
        </h2>
        <div>
          <RenderCards
            v-if="searchText"
            :data="searchedResults"
            :title="
              searchedResults.length === 0 ? 'No Search Results Found' : ''
            "
          />
          <RenderCards v-else :data="allPosts" title="" />
        </div>
      </template>
    </div>
  </section>
</template>

<style lang="scss" scoped></style>
